/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TransactionLazyImport = createFileRoute('/transaction')()
const HomeLazyImport = createFileRoute('/home')()
const BucketLazyImport = createFileRoute('/bucket')()

// Create/Update Routes

const TransactionLazyRoute = TransactionLazyImport.update({
  path: '/transaction',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/transaction.lazy').then((d) => d.Route))

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const BucketLazyRoute = BucketLazyImport.update({
  path: '/bucket',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bucket.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bucket': {
      preLoaderRoute: typeof BucketLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/transaction': {
      preLoaderRoute: typeof TransactionLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  BucketLazyRoute,
  HomeLazyRoute,
  TransactionLazyRoute,
])

/* prettier-ignore-end */
